package com.lpoo2401.projetolpooe1_jorgeb.view;

import com.lpoo2401.projetolpooe1_jorgeb.model.Obra;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.swing.JOptionPane;

//@author JRG B

public class Tela_CObra extends javax.swing.JFrame {

    private Obra obra;  // Will be null if adding a new entry
    private EntityManagerFactory emf;
    private Tela_Controle parentFrame;
    
    public Tela_CObra(EntityManagerFactory emf, Tela_Controle parentFrame) {
        this.emf = emf;
        this.parentFrame = parentFrame;
        initComponents();
    }

    // Constructor for editing an existing Obra
    public Tela_CObra(EntityManagerFactory emf, Obra obra, Tela_Controle parentFrame) {
        this.emf = emf;
        this.obra = obra;
        this.parentFrame = parentFrame;
        initComponents();
        populateFields();  // Populate fields with the existing data
    }

    // Method to populate the fields if editing
    private void populateFields() {
        if (obra != null) {
            jTextField_Local.setText(obra.getLocal());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_Salvar = new javax.swing.JButton();
        jButton_Cancel = new javax.swing.JButton();
        jLabel_Local = new javax.swing.JLabel();
        jTextField_Local = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton_Salvar.setText("Salvar");
        jButton_Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SalvarActionPerformed(evt);
            }
        });

        jButton_Cancel.setText("Cancelar");
        jButton_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CancelActionPerformed(evt);
            }
        });

        jLabel_Local.setText("Local");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_Local)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_Salvar)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_Cancel))
                    .addComponent(jTextField_Local))
                .addContainerGap(284, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Local)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_Local, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Salvar)
                    .addComponent(jButton_Cancel))
                .addContainerGap(208, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SalvarActionPerformed
        EntityManager em = emf.createEntityManager();
        em.getTransaction().begin();

        try {
            if (obra == null) {
                // Adding new Obra
                obra = new Obra();
            }
            // Setting/Updating values
            obra.setLocal(jTextField_Local.getText());

            if (obra.getId() != null) {
                em.merge(obra);  // Merges the new or updated Obra into the database
            } else {
                em.persist(obra);
            }

            em.getTransaction().commit();
            parentFrame.attList();  // Refresh the list in the parent frame
            this.dispose();  // Close the form
        } catch (Exception e) {
            em.getTransaction().rollback();
            JOptionPane.showMessageDialog(this, "Erro na tentativa de salvar Obra: " + e.getMessage());
        } finally {
            em.close();
        }
    }//GEN-LAST:event_jButton_SalvarActionPerformed

    private void jButton_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton_CancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Cancel;
    private javax.swing.JButton jButton_Salvar;
    private javax.swing.JLabel jLabel_Local;
    private javax.swing.JTextField jTextField_Local;
    // End of variables declaration//GEN-END:variables
}
