package com.lpoo2401.projetolpooe1_jorgeb.view;

import com.lpoo2401.projetolpooe1_jorgeb.model.Caminhao;
import com.lpoo2401.projetolpooe1_jorgeb.model.Motoristas;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

//@author JRG B

public class Tela_CMotorista extends javax.swing.JFrame {

    private Motoristas motorista;
    private EntityManagerFactory emf;
    private Tela_Controle parentFrame;
    
    public Tela_CMotorista(EntityManagerFactory emf, Tela_Controle parentFrame) {
        this.emf = emf;
        this.parentFrame = parentFrame;
        initComponents();
        loadComboBoxData();
    }
    // Constructor for editing an existing Motorista
    public Tela_CMotorista(EntityManagerFactory emf, Motoristas motorista, Tela_Controle parentFrame) {
        this.emf = emf;
        this.motorista = motorista;
        this.parentFrame = parentFrame;
        initComponents();
        loadComboBoxData();
        preencherCampos();
    }
    
    private void loadComboBoxData() {
        EntityManager em = emf.createEntityManager();

        // Load Caminhao entities
        List<Caminhao> caminhoes = em.createQuery("SELECT c FROM Caminhao c", Caminhao.class).getResultList();
        DefaultComboBoxModel<Caminhao> caminhaoModel = new DefaultComboBoxModel<>(caminhoes.toArray(new Caminhao[0]));
        jComboBox_Caminhao.setModel(caminhaoModel);

        em.close();
    }
    // Metodo para preencher os campos na edicao
    private void preencherCampos() {
        if (motorista != null) {
            jTextField_CPF.setText(motorista.getCPF().toString());
            jTextField_Nome.setText(motorista.getNome());
            jTextField_Cel.setText(motorista.getNumero_celular());
            jTextField_CPF.setEditable(false);  // CPF should not be editable during edit
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_CPF = new javax.swing.JLabel();
        jTextField_CPF = new javax.swing.JTextField();
        jLabel_Nome = new javax.swing.JLabel();
        jTextField_Nome = new javax.swing.JTextField();
        jLabel_Cel = new javax.swing.JLabel();
        jTextField_Cel = new javax.swing.JTextField();
        jButton_Salvar = new javax.swing.JButton();
        jButton_Cancel = new javax.swing.JButton();
        jComboBox_Caminhao = new javax.swing.JComboBox<>();
        jLabel_Caminhao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel_CPF.setText("CPF");

        jLabel_Nome.setText("Nome");

        jLabel_Cel.setText("Celular");

        jButton_Salvar.setText("Salvar");
        jButton_Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SalvarActionPerformed(evt);
            }
        });

        jButton_Cancel.setText("Cancelar");
        jButton_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CancelActionPerformed(evt);
            }
        });

        jLabel_Caminhao.setText("Caminhao:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_Salvar)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_Cancel))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextField_Nome, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                        .addComponent(jLabel_Nome)
                        .addComponent(jLabel_CPF)
                        .addComponent(jTextField_CPF)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Cel)
                    .addComponent(jTextField_Cel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_Caminhao, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Caminhao))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_CPF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_CPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_Cel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_Cel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_Nome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_Caminhao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox_Caminhao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Salvar)
                    .addComponent(jButton_Cancel))
                .addContainerGap(148, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SalvarActionPerformed
        EntityManager em = emf.createEntityManager();
        em.getTransaction().begin();

        try {
            if (motorista == null) {
                // Adding new Motorista
                motorista = new Motoristas();
                motorista.setCPF(Integer.parseInt(jTextField_CPF.getText()));
            }
            // Setting/Updating values
            motorista.setNome(jTextField_Nome.getText());
            motorista.setNumero_celular(jTextField_Cel.getText());
            motorista.setCaminhao((Caminhao) jComboBox_Caminhao.getSelectedItem());

            if (motorista.getCPF() != null) {
                em.merge(motorista);  // Merges the new or updated Motorista into the database
            } else {
                em.persist(motorista);
            }

            em.getTransaction().commit();
            parentFrame.attList();  // Refresh the list in the parent frame
            this.dispose();  // Close the form
        } catch (Exception e) {
            em.getTransaction().rollback();
            JOptionPane.showMessageDialog(this, "Erro na tentativa de salvar o Motorista: " + e.getMessage());
        } finally {
            em.close();
        }
    }//GEN-LAST:event_jButton_SalvarActionPerformed

    private void jButton_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton_CancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Cancel;
    private javax.swing.JButton jButton_Salvar;
    private javax.swing.JComboBox<Caminhao> jComboBox_Caminhao;
    private javax.swing.JLabel jLabel_CPF;
    private javax.swing.JLabel jLabel_Caminhao;
    private javax.swing.JLabel jLabel_Cel;
    private javax.swing.JLabel jLabel_Nome;
    private javax.swing.JTextField jTextField_CPF;
    private javax.swing.JTextField jTextField_Cel;
    private javax.swing.JTextField jTextField_Nome;
    // End of variables declaration//GEN-END:variables
}
